### ISSUE TITLE
[BUG] Password Box missing

### ISSUE THREAD

**Issue by lgdsgd2000** [TheWisker/Shikai#15] opened 2024-03-08 14:59 UTC
### Explanation

refer the title, can't  enter password

### Shikai Version

v1.5.1

### Linux Distro

Arch

### LightDM Version

v1.32 from extra repo

### Greeter Version

v3.5.2 from aur

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment] 2024-11-11 11:02
Yes, it could be an issue with the git version. From what I checked I cannot reproduce the issue. I will mark this as closed as no one else has reported this issue.

**Closed** 2024-11-11 11:02 UTC
Labels: bug
