### ISSUE TITLE
sleep not working

### ISSUE THREAD

**Issue by skarpinis** [TheWisker/Shikai#19] opened 2024-10-22 14:01 UTC
### Explanation

when i press sleep get error
![error](https://github.com/user-attachments/assets/b37e809f-c83e-455b-80c1-4e9e086b221a)

### Steps to reproduce

on login screen press sleep

### Shikai Version

v1.5.1

### Linux Distro

arch

### LightDM Version

latest

### Greeter Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment] 2024-11-14 17:06
I will revise the code that manages the sleep function, but I believe this error is most likely caused by something else.
I tested the sleep function on my machine and it works fine, I am also using arch!
Here are my guesses:
- Your current machine does not support Sleeping
- LightDM is not capable of sleeping with your current configuration
And here is a list of ways you can check to find out if the cause is one of them:
- Sleep your computer from inside a session, either a WM or a DE.
- Load another web-greeter theme and try to Sleep from there.
- Try to sleep using a shell command, like `systemctl sleep`.

Finally, if it was caused by any of those guesses, you can do one of the following:
- Disable the sleep option from the Shikai setting menu
or
- Try to fix the sleep option on your machine

**Comment by TheWisker** [comment] 2024-11-17 18:18
I will close the issue now, if you have any further problems feel free to open a discussion :)

**Closed by TheWisker** 2024-11-17 18:18 UTC
Labels: bug

**Comment by skarpinis** [comment] 2024-11-17 21:37
Thank you
